version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4
    steps:
      - checkout
      - run: echo "hello world"
  deploy:
    docker:
      - image: circleci/node:4
    steps:
      - run: 
        command: node /tmp/deploy_to/current/nodeScript.js

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      